sudo: true
language: python
python:
    # - "2.7"
    - "3.7"
    - "3.8"

env:
    # - DJANGO_VERSION=1.9
    # - DJANGO_VERSION=1.10.8
    # - DJANGO_VERSION=1.11
    - DJANGO_VERSION=2.0
    - DJANGO_VERSION=2.1
    - DJANGO_VERSION=2.2
    - DJANGO_VERSION=3.0


addons:
  apt:
    packages:
    - nginx

install:
    - sudo ln -s tests/ngingx.conf /etc/nginx/sites-enabled/
    - sudo service nginx reload
    - pip install -q Django==$DJANGO_VERSION
    - python setup.py -q install

script:
    - make test
