sudo: true
language: python
python:
    - "2.7"
    - "3.5"
    - "3.6"

env:
    - DJANGO_VERSION=1.9
    - DJANGO_VERSION=1.10
    - DJANGO_VERSION=1.11

addons:
  apt:
    packages:
    - nginx

install:
    - sudo ln -s tests/ngingx.conf /etc/nginx/sites-enabled/
    - sudo service nginx reload
    - pip install -q Django==$DJANGO_VERSION
    - python setup.py -q install

script:
    - make test
