language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"

env:
    - DJANGO_VERSION=1.9
    - DJANGO_VERSION=1.10
    - DJANGO_VERSION=1.11
    - DJANGO_SETTINGS_MODULE=demo.settings

addons:
  apt:
    packages:
    - nginx

install:
    - pip install -q Django==$DJANGO_VERSION
    - python setup.py -q install

script:
    - make test
